apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-poc
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aymanlinuxBoy/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://api.itz-kycw1o.osv.techzone.ibm.com:6443
    namespace: devops

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
