apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-poc
  namespace: devops
spec:
  project: default

  source:
    repoURL: https://github.com/aymanlinuxBoy/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://api.stgocp.mwanitest.local:6443
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
