apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-3
spec:
  selector:
    matchLabels:
      app: myapp-3
  replicas: 6
  template:
    metadata:
      labels:
        app: myapp-3
    spec:
      containers:
      - name: myapp-3
       # image: default-route-openshift-image-registry.apps.stgocp.mwanitest.local/devops/poc-devops:latest
        image: docker.io/nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
