apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-poc
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: docker.io/nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080
